--SELECT * FROM Alunos WHERE Nome LIKE 'Rafael'
--SELECT * FROM Alunos WHERE Nome LIKE 'R%'
--SELECT * FROM Alunos WHERE Nome LIKE '%o'
--SELECT * FROM Alunos WHERE Nome LIKE '%a%'
SELECT * FROM Alunos WHERE Nome LIKE 'r%l'